### PR TITLE
Add AUTO_REFRESH setting

### PR DESCRIPTION
**Pull request by rphlo**
Implement enhancement https://github.com/James1345/django-rest-knox/issues/37

### CODE REVIEW

**Comment by belugame** [comment]
@rphlo thanks a lot for this feature. I m happy to merge it in. 2 things. 
a) we need unit tests that cover it e.g. assert that the token expiry timestamp is (not) extended when expected. 
b) I would make the 1 second threshold bigger to avoid hitting the database more than it is useful for this usecase. 5 or even 10 seconds seems reasonable for me

**Comment by rphlo** [comment]
@belugame what about using freezegun in tests? This would add a dependency but would bring many benefit in my point of view for the tests...

**Comment by belugame** [comment]
@rphlo sure, I m familiar with freezegun. Feel free to add it to tox.ini

**Comment by belugame** [comment]
@rphlo Thank you for the work again, I extended your unit tests and tweaked things elsewhere unrelated to your changes. Glad to have your review my changes. https://github.com/James1345/django-rest-knox/pull/105

**Pull request merged**
