### PR TITLE
Send out signals upon login and logout

### PR DESCRIPTION
**Pull request by blaklites**
This pull requests enables the sending of user_logged_in and user_logged_out signals upon login and logout.

@James1345 can this be merged?

### CODE REVIEW

**Comment by blaklites** [comment]
@James1345 any thoughts on this yet :) ?

**Comment by James1345** [comment]
I have no strong objections to this addition - just not had any time to look at this project since you sent the request

**Comment by blaklites** [comment]
Ah alright, can we merge it then?

**Comment by blaklites** [comment]
@James1345 ? :)

**Comment by James1345** [comment]
I have merged this in on develop (had to do manually as github's auto-merge uses master). Thanks for the changes

**Pull request closed without merging**
