### PR TITLE
Add docker support to run the tests

### PR DESCRIPTION
**Pull request by johnraz**
This was handy to run the all matrix of tests locally and could help others.

On the other hand I would totally understand if you don't like the Docker dependency or don't want to maintain something like this ✌️

### CODE REVIEW

**Comment by James1345** [comment]
I like this idea too.

**Comment by johnraz** [comment]
@belugame the Docker volume mount seems to be struggling with permissions, it can be due to a lot of different things... Also keep in mind that containers are just namespacing things, 

- It may just be that for some reason you have some permissions fuckup in your `.tox` dir.

I tried to create such a use case on my laptop, see below:

```
┌─[john][mbp-john][/tmp/test-dck]
└─▪ docker run --rm -v $(pwd):/hello/ -w /hello themattrix/tox mkdir test
┌─[john][mbp-john][/tmp/test-dck]
└─▪ ls -l
total 0
drwxr-xr-x  2 john  wheel  64  5 oct 13:33 test
┌─[john][mbp-john][/tmp/test-dck]
└─▪ sudo chown root test/
┌─[john][mbp-john][/tmp/test-dck]
└─▪ docker run --rm -v $(pwd):/hello/ -w /hello themattrix/tox mkdir test/fail
mkdir: cannot create directory ‘test/fail’: Permission denied
```

It clearly fails when the host mounted dir is owned by root while docker is run by my user "john".

Can you check if there is something weird with the permissions for `.tox/log/tox-1.log`.

May I ask which platform you are on? Which filesystem? Anything exotic like an NFS mount or something?

As a last resort, could you try removing the `.tox` directory completely and run the script again?

**Comment by johnraz** [comment]
And I added the note in the readme.

**Comment by belugame** [comment]
I wiped the folder .tox and restarted the script, but it did not help. :-/

```
[local-docker-run-tests ✔] [~/repos/django-rest-knox]$ rm -rf .tox                  [INS]
[local-docker-run-tests ✔] [~/repos/django-rest-knox]$ ./docker-run-tests.sh        [INS]
Traceback (most recent call last):
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_error.py", line 66, in checked_call
    return func(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: '/django-rest-knox/.tox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.pyenv/versions/3.7.0/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tox/session.py", line 39, in cmdline
    main(args)
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tox/session.py", line 45, in main
    retcode = Session(config).runcommand()
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/tox/session.py", line 369, in __init__
    config.logdir.ensure(dir=1)
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_path/local.py", line 530, in ensure
    return p._ensuredirs()
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_path/local.py", line 512, in _ensuredirs
    parent._ensuredirs()
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_path/local.py", line 515, in _ensuredirs
    self.mkdir()
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_path/local.py", line 465, in mkdir
    py.error.checked_call(os.mkdir, fspath(p))
  File "/.pyenv/versions/3.7.0/lib/python3.7/site-packages/py/_error.py", line 86, in checked_call
    raise cls("%s%r" % (func.__name__, args))
py.error.EACCES: [Permission denied]: mkdir('/django-rest-knox/.tox',)](url)
```

**Comment by johnraz** [comment]
Hey @belugame, that's disappointing 😞

There is clearly an issue with your Docker daemon...

Are you using Docker in other scenarios?
Did you ever witness writing successfully to a volume mount before?

And also from before:
> May I ask which platform you are on? Which filesystem?

I'm 100% sure this is a Docker or OS related issue as it works on my Mac using Docker for mac and on my Ubuntu box using regular Docker binary.

**Comment by belugame** [comment]
I have tried it on two machines running Ubuntu 16.04, Docker version 18.06.1-ce, build e68fc7a
Filesystems are ext4. I do use several other docker containers with volumens on them, have not seen this error before.

**Comment by johnraz** [comment]
I realise now that I have been running this only on my Mac since day 1...

I was able to reproduce on the linux box indeed...
Will look into it 👍

**Comment by johnraz** [comment]
@belugame: I think it should work now, could you please try again?

**Comment by belugame** [comment]
works like a charm! :+1:

**Pull request merged**
